### ISSUE TITLE
Implementation uses non-standard capability short hash for Sender Validation

### ISSUE THREAD

**Issue by derekm** [moneybutton/express-paymail#3]
express-paymail uses "c318d09ed403":

https://github.com/moneybutton/express-paymail/blob/master/src/constants.js#L4

but the spec calls for "6745385c3fc0":

http://bsvalias.org/04-02-sender-validation.html

Is your impl developed against an older version of the spec?

**Comment by hojarasca** [comment]
True. fixing now.

**Comment by hojarasca** [comment]
Fixed
