### ISSUE TITLE
Implementation uses non-standard field names in Basic Address Resolution

### ISSUE THREAD

**Issue by derekm** [moneybutton/express-paymail#4]
express-paymail uses `senderPaymail` in the sender request:

https://github.com/moneybutton/express-paymail/blob/master/src/buildGetPaymentDestinationRouter.js#L11

but the spec calls for `senderHandle`:

http://bsvalias.org/04-01-basic-address-resolution.html#sender-request

**Comment by hojarasca** [comment]
Fixed: https://github.com/moneybutton/express-paymail/commit/aacf829948f9492bc7eeafe9f01bd3e95248fc8f
