### ISSUE TITLE
"Invalid sender paymail" error has a bad email validating regex

### ISSUE THREAD

**Issue by derekm** [moneybutton/express-paymail#5]
The regex here is too simplistic and too strict to validate email addresses:

https://github.com/moneybutton/express-paymail/blob/master/src/buildGetPaymentDestinationRouter.js#L28

A better JS-compatible regex to use can be found in the second note of this section in the WhatWG's HTML Living Standard:

https://html.spec.whatwg.org/multipage/input.html#e-mail-state-(type=email)

or...
```/^[a-zA-Z0-9.!#$%&'*+\/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$/```

In my Java implementation of Paymail, I use this shorter & faster regex:
```"[a-zA-Z0-9.!#$%&'*+\\/=?^_`{|}~-]+@[a-zA-Z0-9](?:(?:[a-zA-Z0-9-]*|(?<!-)\\.(?![-.]))*[a-zA-Z0-9]+)?"```

**Comment by hojarasca** [comment]
That regex is simple and really generic on purpose.

The idea is discard things that are obviously wrong, but then, if the handle is not correct the receiver service is going to reject it. We don't need a really strong validation there. Just discard things that are obviously wrong.

I noticed that I didn't scape the dot. That was a mistake. This is my idea for this regex:

``` javascript
/^\S+@\S+\.\S+$/
```

That would be:

1. start of string
2. Anything with no spaces at least one letter
3. at symbol
4. anything with no spaces
5. a dot
6. anything with no spaces 
7. end of string

That's really easy to understand, and at the end of the day this validation doesn't matter, real validation goes when the service look up for the paymail handle.

**Comment by derekm** [comment]
Your regex validates such hostnames as `example..com`, which is obviously wrong and should be rejected from the outset.

The regex from the HTML standard doesn't suffer from this problem, and it is easily documented since you can refer to the standard. You'll then be compatible with the expectations of mail servers & web browsers.

For more, see this stackoverflow: https://stackoverflow.com/a/18494710/2355587

**Comment by hojarasca** [comment]
Fixed on: https://github.com/moneybutton/express-paymail/commit/862ad241e5b7458ba8f8444015deff8cb246d4c9
